name: Estado ICBS Automático

on:
  schedule:
    - cron: "*/30 * * * *"  # Cada 30 minutos
  workflow_dispatch:  # Permite ejecutarlo manualmente también

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Ejecutar script de extracción
        run: python extractor_estado.py

      - name: Confirmar y hacer push si hubo cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add proxy_estado_iframe.html
          git commit -m "Actualización automática del estado" || echo "Sin cambios"
          git push
