name: Actualizar llamados

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install
          pip install beautifulsoup4

      - name: Ejecutar script de extracción
        run: python extractor_llamados.py

      - name: Subir archivo actualizado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Actualización automática de llamados
          file_pattern: llamados_actualizado.html
