name: Actualizar llamados

on:
  schedule:
    - cron: "*/10 * * * *"  # Cada 10 minutos
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps

      - name: Ejecutar extractor de llamados
        run: python extractor_llamados.py
      - name: Commit y push de 'llamados_actualizado.html'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add llamados_actualizado.html
          git commit -m "Actualiza últimos llamados"
          git push
